[package]
name = "haven"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
env_logger = "0.10.0"
log = "0.4.19"
octocrab = "0.25.1"
reqwest = "0.11.18"
serenity = "0.11.5"
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }
